name: terphenyl
channels:
  - conda-forge
  - omnia
  - openeye
dependencies:
  - python
  - ca-certificates
  - openssl
  - ambertools
  - openeye-toolkits
  - psi4
  - dftd3-python
  - xtb-python
  - mbuild
  - tqdm
  - pytest
  - rdkit
  - pyyaml
  - mdtraj
  - numpy
  - matplotlib
  - scikit-learn
  - mdanalysis
  - signac
  - signac-flow
  - panedr
  - pandas
  - seaborn
  - gromacs
  - openbabel
  - certifi
  - openmm
  - openff-units
  - cachetools
  - xmltodict
  - openff-toolkit
  - openff-bespokefit=0.4.0
  - openff-qcsubmit=0.50
  - qcelemental=0.28
  - openff-interchange
  - qcportal
  - natsort
  - mbuild
# prefix: /home/lenny/miniforge3/envs/ts_env
